application: your-app-id
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6

handlers:
- url: /assets
  static_dir: public/assets
- url: /css
  static_dir: public/css
- url: /js
  static_dir: public/js
- url: /.*
  script: routes.drawPage.application
